### ISSUE TITLE
Not working with phoenix in recent versions

### ISSUE THREAD

**Issue by ricardopacheco** [mathieuprog/i18n_helpers#1]
```elixir
defp deps do
   [
     ...
     {:phoenix, "~> 1.6.2"},
     {:i18n_helpers, "~> 0.11.0"}
   ]
end

```
❯ mix deps.get
Resolving Hex dependencies...

Failed to use "mime" (versions 2.0.0 to 2.0.2) because
  phoenix_live_dashboard (version 0.6.1) requires ~> 1.6.0
  swoosh (versions 1.4.0 to 1.5.2) requires ~> 1.1 or ~> 2.0

Failed to use "phoenix_html" because
  ex_money (version 5.7.0) requires ~> 2.0 or ~> 3.0 *
  i18n_helpers (version 0.11.0) requires ~> 2.13
  phoenix_live_view (versions 0.16.1 to 0.17.2) requires ~> 3.0
  phoenix_view (version 1.0.0) requires ~> 2.14.2 or ~> 3.0

Failed to use "phoenix_html" because
  ex_money (version 5.7.0) requires ~> 2.0 or ~> 3.0 *
  i18n_helpers (version 0.11.0) requires ~> 2.13
  phoenix_live_view (versions 0.17.3 to 0.17.5) requires ~> 3.1
  phoenix_view (version 1.0.0) requires ~> 2.14.2 or ~> 3.0

Failed to use "phoenix_html" because
  ex_money (version 5.7.0) requires ~> 2.0 or ~> 3.0 *
  i18n_helpers (version 0.11.0) requires ~> 2.13
  phoenix_live_view (version 0.16.0) requires ~> 3.0.0
  phoenix_view (version 1.0.0) requires ~> 2.14.2 or ~> 3.0
```

**Comment by mathieuprog** [comment]
It seems like we need to update some deps? can you submit a PR?

**Comment by ricardopacheco** [comment]
@mathieuprog done, [here](https://github.com/mathieuprog/i18n_helpers/pull/2)

**Comment by mathieuprog** [comment]
Cool:) You can depend on 0.12.0
