### ISSUE TITLE
Missing 3-arity

### ISSUE THREAD

**Issue by decioferreira** [mathieuprog/i18n_helpers#9]
Hi, I was trying to pass the `on_replace` option to `translatable_has_many` when I noticed this is not allowed.

After a quick search I've noticed that this has already been addressed in two PRs: #4 and #7.

Is there any plan to support passing options onto the exposed functions? Thank you.

PS: thanks for the great work on this package, really appreciate it!

**Comment by mathieuprog** [comment]
Merged
